services:
  db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_DB=chatdb
      - POSTGRES_USER=chat
      - POSTGRES_PASSWORD=chatpass
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U chat -d chatdb"]
      interval: 5s
      timeout: 3s
      retries: 10
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        BASE_IMAGE: ${BASE_IMAGE:-node:20-alpine}
    environment:
      - PORT=2001
      - DATABASE_URL=postgresql://chat:chatpass@db:5432/chatdb
    ports:
      - "2001:2001"
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_WS_URL: ${WS_URL:-http://localhost:2001}
        BASE_IMAGE: ${BASE_IMAGE:-node:20-alpine}
    environment:
      - VITE_WS_URL=${WS_URL:-http://localhost:2001}
    ports:
      - "2002:2002"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  pgdata:


